### ISSUE TITLE
Dependency Conflict: Unable to Resolve Dependency Tree with React 18.2.0

### ISSUE THREAD

**Issue by pratham-jaiswal** [hack5hu/react-native-mobile-sms#2]
I encountered a dependency conflict while trying to install react-native-mobile-sms in my project using the following command:

```sh
npm i react-native-mobile-sms
````

Error Output:
```sh
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: signal@1.0.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.8.1" from react-native-mobile-sms@0.1.1
npm error node_modules/react-native-mobile-sms
npm error   react-native-mobile-sms@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\PRATHAM\AppData\Local\npm-cache\_logs\2024-09-01T13_04_52_087Z-eresolve-report.txt

npm error A complete log of this run can be found in: C:\Users\PRATHAM\AppData\Local\npm-cache\_logs\2024-09-01T13_04_52_087Z-debug-0.log
```

The complete log pasted from the log file:
```txt
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.7.0
2 info using node@v20.14.0
3 silly config:load:file:C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\npmrc
4 silly config:load:file:D:\React Native Projects\signal\.npmrc
5 silly config:load:file:C:\Users\PRATHAM\.npmrc
6 silly config:load:file:C:\Program Files\nodejs\etc\npmrc
7 verbose title npm i react-native-mobile-sms
8 verbose argv "i" "react-native-mobile-sms"
9 verbose logfile logs-max:10 dir:C:\Users\PRATHAM\AppData\Local\npm-cache\_logs\2024-09-01T13_04_52_087Z-
10 verbose logfile C:\Users\PRATHAM\AppData\Local\npm-cache\_logs\2024-09-01T13_04_52_087Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly fetch manifest react-native-mobile-sms@*
15 http fetch GET 200 https://registry.npmjs.org/react-native-mobile-sms 635ms (cache hit)
16 silly fetch manifest react@18.2.0
17 http fetch GET 200 https://registry.npmjs.org/react 34ms (cache hit)
18 silly fetch manifest react@^16.8.1
19 verbose stack Error: unable to resolve dependency tree
19 verbose stack     at #failPeerConflict (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1386:25)
19 verbose stack     at #loadPeerSet (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1352:33)
19 verbose stack     at async #buildDepStep (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:923:11)
19 verbose stack     at async Arborist.buildIdealTree (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:203:7)
19 verbose stack     at async Promise.all (index 1)
19 verbose stack     at async Arborist.reify (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:131:5)
19 verbose stack     at async Install.exec (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\lib\commands\install.js:150:5)
19 verbose stack     at async module.exports (C:\Users\PRATHAM\AppData\Roaming\nvm\v20.14.0\node_modules\npm\lib\cli\entry.js:74:5)
20 verbose cwd D:\React Native Projects\signal
21 verbose Windows_NT 10.0.22631
22 verbose node v20.14.0
23 verbose npm  v10.7.0
24 error code ERESOLVE
25 error ERESOLVE unable to resolve dependency tree
26 error
27 error While resolving: signal@1.0.0
27 error Found: react@18.2.0[2m[22m
27 error [2mnode_modules/react[22m
27 error   react@"18.2.0" from the root project
27 error
27 error Could not resolve dependency:
27 error [95mpeer[39m react@"^16.8.1" from react-native-mobile-sms@0.1.1[2m[22m
27 error [2mnode_modules/react-native-mobile-sms[22m
27 error   react-native-mobile-sms@"*" from the root project
27 error
27 error Fix the upstream dependency conflict, or retry
27 error this command with --force or --legacy-peer-deps
27 error to accept an incorrect (and potentially broken) dependency resolution.
28 error
28 error
28 error For a full report see:
28 error C:\Users\PRATHAM\AppData\Local\npm-cache\_logs\2024-09-01T13_04_52_087Z-eresolve-report.txt
29 verbose exit 1
30 verbose code 1
31 silly unfinished npm timer reify 1725195893198
32 silly unfinished npm timer reify:loadTrees 1725195893208
33 silly unfinished npm timer idealTree:buildDeps 1725195894521
34 silly unfinished npm timer idealTree:#root 1725195894522
35 error A complete log of this run can be found in: C:\Users\PRATHAM\AppData\Local\npm-cache\_logs\2024-09-01T13_04_52_087Z-debug-0.log
```

Steps to Reproduce:
1. Create a new React Native project or use an existing one with React version 18.2.0
2. Run `npm install react-native-mobile-sms`

**Comment by roganantonys** [comment]
i too facing the same error, how do you resolve it @pratham-jaiswal

**Comment by pratham-jaiswal** [comment]
@roganantonys  I couldn't
